from __future__ import annotations

import random

import pygame

from algolab.simulation.simulator import Simulator
from algolab.topics.sorting.simulation import (
    BubbleSortSimulator,
    HeapSortSimulator,
    InsertionSortSimulator,
    MergeSortSimulator,
    QuickSortSimulator,
    SelectionSortSimulator,
)
from algolab.ui.components.button import Button
from algolab.ui.components.info_panel import InfoPanel
from algolab.ui.components.numeric_input import NumericInput
from algolab.ui.components.surface import draw_panel, draw_toggle_button
from algolab.ui.screens.screen import Screen
from algolab.ui.theme import Color, Font


class SortingRaceScreen(Screen):
    """
    Pick two sorting algorithms and race them on the same shared array.

    Both simulators are stepped together on one shared timer tick,
    each independently stopping once it reaches its own end -- this is
    what actually makes it a race rather than two separate playbacks:
    same real-time cadence for both, and whichever needs fewer steps
    visibly finishes first.

    This screen never touches SortArray or the sorting model at all;
    it generates its own array directly (same as every other topic's
    Randomize button does) and calls the same simulator_class().run()
    interface SortingScreen already uses, since there's no persistent
    structure to keep afterward -- the race is purely a visual
    comparison, with nothing to commit.
    """

    ALGORITHMS = {
        "Bubble": BubbleSortSimulator,
        "Selection": SelectionSortSimulator,
        "Insertion": InsertionSortSimulator,
        "Merge": MergeSortSimulator,
        "Quick": QuickSortSimulator,
        "Heap": HeapSortSimulator,
    }

    # Duplicated from SortingScreen's own InfoPanel rows rather than
    # imported, deliberately -- SortingScreen imports THIS file (to
    # open the Compare screen), so importing the other way back would
    # create a circular import. This list is small and static enough
    # that keeping two copies in sync by hand is a low-risk tradeoff.
    COMPLEXITY_ROWS = [
        ("Bubble Sort", "O(n^2) avg", "Best O(n), worst O(n^2)"),
        ("Selection Sort", "O(n^2) avg", "Best and worst also O(n^2)"),
        ("Insertion Sort", "O(n^2) avg", "Best O(n), worst O(n^2)"),
        ("Merge Sort", "O(n log n) avg", "Best and worst also O(n log n)"),
        ("Quick Sort", "O(n log n) avg", "Best O(n log n), worst O(n^2)"),
        ("Heap Sort", "O(n log n) avg", "Best and worst also O(n log n)"),
    ]

    def __init__(self, surface: pygame.Surface, on_back=None) -> None:
        super().__init__(surface, on_back)

        self.control_font = Font.H1()
        self.section_font = Font.H2()
        self.small_font = Font.SMALL()
        self.label_font = Font.LABEL()
        self.value_font = Font.LABEL()

        self.size_input = NumericInput(pygame.Rect(160, 145, 75, 30), 12)

        self.randomize_button = Button(
            pygame.Rect(15, 179, 220, 34), "Randomize", variant="primary"
        )

        self.algorithm_a_label: str | None = None
        self.algorithm_b_label: str | None = None

        self.algorithm_a_buttons = self._create_algorithm_buttons(250)
        self.algorithm_b_buttons = self._create_algorithm_buttons(435)

        self.start_button = Button(
            pygame.Rect(15, 590, 220, 40), "Start Race", variant="primary"
        )

        self.info_button = Button(
            pygame.Rect(surface.get_width() - 115, 15, 100, 38),
            "Info",
        )
        self.info_panel = InfoPanel(
            "Sorting - Time Complexity",
            self.COMPLEXITY_ROWS,
        )

        self.navigation_buttons = self._create_navigation_buttons()

        for index, button in enumerate(self.speed_buttons):
            button.rect = pygame.Rect(15 + index * 62, 700, 58, 28)

        # The shared array both algorithms race on. Regenerated by
        # Randomize; auto-populated here so the screen isn't empty on
        # first arrival, matching SortingScreen's own default.
        self.shared_values: list[int] = []
        self._randomize()

        # Two independent Simulators, driven by ONE shared timer (see
        # class docstring). current_simulation_a/b hold the Simulation
        # objects themselves (not just their Simulator), since their
        # len(.states) is needed for each side's step counter and for
        # deciding which algorithm finished in fewer steps.
        self.simulator_a = Simulator()
        self.simulator_b = Simulator()
        self.current_simulation_a = None
        self.current_simulation_b = None

        self.is_playing = False
        self.step_timer = 0.0
        self.step_interval = 0.6

        self.error_message: str | None = None

    # ------------------------------------------------------------------
    # UI creation
    # ------------------------------------------------------------------

    def _create_algorithm_buttons(self, y_start: int) -> dict[str, Button]:
        labels = list(self.ALGORITHMS.keys())
        buttons = {}

        for index, label in enumerate(labels):
            row = index // 2
            column = index % 2

            x = 15 if column == 0 else 130
            width = 110 if column == 0 else 105
            y = y_start + row * 38

            buttons[label] = Button(pygame.Rect(x, y, width, 34), label)

        return buttons

    def _create_navigation_buttons(self) -> list[Button]:
        labels = ["|<", "<", ">", ">|", "P"]

        buttons = []
        x = 15
        y = 738
        width = 40
        height = 35
        spacing = 45

        for index, label in enumerate(labels):
            buttons.append(
                Button(pygame.Rect(x + index * spacing, y, width, height), label)
            )

        return buttons

    # ------------------------------------------------------------------
    # Event handling
    # ------------------------------------------------------------------

    def handle_event(self, event: pygame.event.Event) -> None:
        if self.info_panel.handle_event(event):
            return

        if self.handle_back_event(event):
            return

        if self.handle_speed_event(event):
            return

        self.size_input.handle_event(event)

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_p:
                self._handle_navigation(4)
                return
            if event.key == pygame.K_LEFT:
                self._handle_navigation(1)
                return
            if event.key == pygame.K_RIGHT:
                self._handle_navigation(2)
                return

        if self.randomize_button.handle_event(event):
            self._randomize()

        if self.info_button.handle_event(event):
            self.info_panel.open()

        for label, button in self.algorithm_a_buttons.items():
            if button.handle_event(event):
                self._select_algorithm("a", label)

        for label, button in self.algorithm_b_buttons.items():
            if button.handle_event(event):
                self._select_algorithm("b", label)

        if self.start_button.handle_event(event):
            self._start_race()

        for index, button in enumerate(self.navigation_buttons):
            if button.handle_event(event):
                self._handle_navigation(index)

    def _select_algorithm(self, slot: str, label: str) -> None:
        """
        Choosing (or changing) either algorithm resets any race in
        progress -- changing horses mid-race doesn't mean anything,
        the same reasoning every other screen already uses when an
        editing action cancels an in-flight simulation.
        """

        if slot == "a":
            self.algorithm_a_label = label
        else:
            self.algorithm_b_label = label

        self._reset_race()

    def _randomize(self) -> None:
        size = max(3, min(30, self.size_input.value))

        self.shared_values = [random.randint(5, 95) for _ in range(size)]

        self._reset_race()

    def _reset_race(self) -> None:
        self.simulator_a = Simulator()
        self.simulator_b = Simulator()
        self.current_simulation_a = None
        self.current_simulation_b = None
        self.is_playing = False
        self.step_timer = 0.0
        self.error_message = None

    def _start_race(self) -> None:
        if self.algorithm_a_label is None or self.algorithm_b_label is None:
            self.error_message = "Select an algorithm for both A and B first."
            return

        if not self.shared_values:
            self.error_message = "Randomize an array first."
            return

        simulator_a_class = self.ALGORITHMS[self.algorithm_a_label]
        simulator_b_class = self.ALGORITHMS[self.algorithm_b_label]

        # Independent copies passed to each, defensively, in case a
        # simulator's run() ever mutates its input list in place --
        # each side must race on its own untouched copy of the same
        # starting values.
        simulation_a = simulator_a_class().run(list(self.shared_values))
        simulation_b = simulator_b_class().run(list(self.shared_values))

        self.simulator_a = Simulator()
        self.simulator_b = Simulator()

        self.simulator_a.load_states(list(simulation_a.states))
        self.simulator_b.load_states(list(simulation_b.states))

        self.current_simulation_a = simulation_a
        self.current_simulation_b = simulation_b

        self.step_timer = 0.0
        self.is_playing = True
        self.error_message = None

    def _handle_navigation(self, index: int) -> None:
        if self.current_simulation_a is None or self.current_simulation_b is None:
            return

        if index == 0:
            self.simulator_a.history.previous_to_start()
            self.simulator_b.history.previous_to_start()
        elif index == 1:
            self.simulator_a.previous()
            self.simulator_b.previous()
        elif index == 2:
            self._step_forward()
        elif index == 3:
            while self.simulator_a.can_go_forward:
                self.simulator_a.next()
            while self.simulator_b.can_go_forward:
                self.simulator_b.next()
            self.is_playing = False
        elif index == 4:
            self.is_playing = not self.is_playing

    def _step_forward(self) -> None:
        """
        Advance whichever simulator hasn't finished yet by one step.
        Each side is guarded independently, since the two algorithms
        will almost always reach their own end after a different
        number of steps -- an algorithm that's already finished simply
        holds at its final (sorted) state while the other keeps going.
        """

        if not self.simulator_a.is_at_end:
            self.simulator_a.next()

        if not self.simulator_b.is_at_end:
            self.simulator_b.next()

    # ------------------------------------------------------------------
    # Update
    # ------------------------------------------------------------------

    def update(self, dt: float) -> None:
        self.update_back_button(dt)
        self.update_speed_buttons(dt)

        self.randomize_button.update(dt)
        self.info_button.update(dt)
        self.start_button.update(dt)

        for button in self.algorithm_a_buttons.values():
            button.update(dt)

        for button in self.algorithm_b_buttons.values():
            button.update(dt)

        self.start_button.enabled = (
            self.algorithm_a_label is not None
            and self.algorithm_b_label is not None
            and bool(self.shared_values)
        )

        for button in self.navigation_buttons:
            button.update(dt)

        if self.current_simulation_a is None or self.current_simulation_b is None:
            return

        if not self.is_playing:
            return

        both_finished = self.simulator_a.is_at_end and self.simulator_b.is_at_end

        if both_finished:
            self.is_playing = False
            return

        self.step_timer += dt

        if self.step_timer >= self.scaled_interval(self.step_interval):
            self.step_timer = 0.0
            self._step_forward()

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def render(self) -> None:
        self.surface.fill(Color.BG)

        self.render_back_button()
        self._render_control_panel()
        self._render_bands()

        self.info_button.render(self.surface)
        self.info_panel.render(self.surface)

    def _draw_text(self, text, position, font, color=Color.TEXT_PRIMARY):
        rendered = font.render(text, True, color)
        self.surface.blit(rendered, position)

    def _render_control_panel(self) -> None:
        panel_rect = pygame.Rect(10, 70, 250, 710)
        draw_panel(self.surface, panel_rect, elevated=True)

        self._draw_text("Compare Algorithms", (25, 80), self.control_font)

        self._draw_text(
            "Shared Array", (25, 112), self.section_font, color=Color.TEXT_SECONDARY
        )
        self._draw_text("Size:", (15, 150), self.small_font, color=Color.TEXT_SECONDARY)
        self.size_input.render(self.surface)
        self.randomize_button.render(self.surface)

        self._draw_text(
            "Algorithm A", (25, 225), self.section_font, color=Color.TEXT_SECONDARY
        )
        for label, button in self.algorithm_a_buttons.items():
            draw_toggle_button(self.surface, button, label == self.algorithm_a_label)

        self._draw_text(
            "Algorithm B", (25, 410), self.section_font, color=Color.TEXT_SECONDARY
        )
        for label, button in self.algorithm_b_buttons.items():
            draw_toggle_button(self.surface, button, label == self.algorithm_b_label)

        self.start_button.render(self.surface)

        if self.error_message is not None:
            error_rect = pygame.Rect(15, 632, 220, 38)
            self._draw_wrapped_text(
                self.error_message, error_rect, self.small_font, Color.STATE_DANGER
            )

        self._draw_text(
            "Simulation", (25, 675), self.section_font, color=Color.TEXT_SECONDARY
        )
        self.render_speed_buttons()

        for index, button in enumerate(self.navigation_buttons):
            if index == 4:
                draw_toggle_button(self.surface, button, self.is_playing)
            else:
                button.render(self.surface)

    def _draw_wrapped_text(self, text, rect, font, color):
        words = text.split()
        lines = []
        current_line = ""

        for word in words:
            test_line = word if not current_line else f"{current_line} {word}"

            if font.size(test_line)[0] <= rect.width:
                current_line = test_line
            else:
                if current_line:
                    lines.append(current_line)
                current_line = word

        if current_line:
            lines.append(current_line)

        line_height = font.get_height()
        y = rect.y

        for line in lines:
            if y + line_height > rect.bottom:
                break

            rendered = font.render(line, True, color)
            self.surface.blit(rendered, (rect.x, y))
            y += line_height

    def _render_bands(self) -> None:
        """
        Two stacked bands, one per algorithm, each spanning the full
        canvas width. Stacked (rather than side by side) so bars stay
        wide enough to read even with 20-30 values, since width isn't
        being split between two charts.
        """

        canvas_left = 280
        canvas_right = self.surface.get_width() - 15
        canvas_width = canvas_right - canvas_left

        band_height = 330

        band_a_top = 80
        band_b_top = band_a_top + band_height + 20

        self._render_band(
            pygame.Rect(canvas_left, band_a_top, canvas_width, band_height),
            self.algorithm_a_label,
            self.simulator_a,
            self.current_simulation_a,
        )

        self._render_band(
            pygame.Rect(canvas_left, band_b_top, canvas_width, band_height),
            self.algorithm_b_label,
            self.simulator_b,
            self.current_simulation_b,
        )

    def _get_state(self, simulator: Simulator):
        if simulator.state is None:
            return None
        return simulator.state.data

    def _render_band(
        self,
        rect: pygame.Rect,
        label: str | None,
        simulator: Simulator,
        simulation,
    ) -> None:
        draw_panel(self.surface, rect, elevated=False)

        header_rect = pygame.Rect(rect.x + 15, rect.y + 10, rect.width - 30, 26)
        self._render_band_header(header_rect, label, simulator, simulation)

        canvas = pygame.Rect(
            rect.x + 15, rect.y + 44, rect.width - 30, rect.height - 60
        )

        state = self._get_state(simulator)
        values = list(state.values) if state is not None else self.shared_values

        if not values:
            return

        self._render_bars(canvas, values, state)

    def _render_band_header(
        self,
        rect: pygame.Rect,
        label: str | None,
        simulator: Simulator,
        simulation,
    ) -> None:
        name = f"{label} Sort" if label is not None else "Not selected"
        self._draw_text(name, (rect.x, rect.y), self.section_font)

        if simulation is None:
            status = "Not started"
        elif simulator.is_at_end:
            status = f"Finished in {len(simulation.states)} steps"
        else:
            # .step lives on the SimulationState wrapper (simulator.state
            # itself), not on its .data payload -- .data only carries
            # values/comparing/swapping/etc., the fields _get_state()
            # returns for bar rendering.
            wrapper_state = simulator.state
            current_step = wrapper_state.step + 1 if wrapper_state is not None else 0
            status = f"Step {current_step}/{len(simulation.states)}"

        status_surface = self.small_font.render(status, True, Color.TEXT_SECONDARY)
        status_rect = status_surface.get_rect(topright=(rect.right, rect.y + 4))
        self.surface.blit(status_surface, status_rect)

    def _bar_color(self, index: int, state) -> tuple[int, int, int]:
        if state is None:
            return Color.STATE_DEFAULT

        if index == state.pivot_index:
            return Color.STATE_REPLACE

        if index in state.swapping:
            return Color.STATE_ACTIVE

        if index in state.comparing:
            return Color.STATE_COMPARING

        if index in state.sorted_indices:
            return Color.STATE_SUCCESS

        return Color.STATE_DEFAULT

    def _render_bars(self, canvas: pygame.Rect, values: list[int], state) -> None:
        n = len(values)
        gap = 3
        bar_width = max(3, (canvas.width - gap * (n - 1)) // n)

        # Scaled against the shared starting array's max, not each
        # band's own current values, so both bands use an identical
        # height scale -- sorting only reorders values, never changes
        # them, so the max is the same number either way, but computing
        # it once from shared_values makes that guarantee explicit.
        max_value = max(self.shared_values) if self.shared_values else 1
        max_value = max_value or 1

        if state is not None and state.active_range is not None:
            low, high = state.active_range
            band_left = canvas.left + low * (bar_width + gap)
            band_width = (high - low) * (bar_width + gap) - gap

            if band_width > 0:
                band_rect = pygame.Rect(band_left, canvas.top, band_width, canvas.height)
                pygame.draw.rect(self.surface, Color.SURFACE_RAISED, band_rect, border_radius=6)

        for index, value in enumerate(values):
            bar_height = int((value / max_value) * (canvas.height - 20))
            bar_height = max(bar_height, 3)

            x = canvas.left + index * (bar_width + gap)
            y = canvas.bottom - bar_height

            rect = pygame.Rect(x, y, bar_width, bar_height)
            color = self._bar_color(index, state)

            pygame.draw.rect(self.surface, color, rect, border_radius=2)